version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo apt-get install -y pyenv
      - run: sudo pip install tox tox-pyenv
      - run: pyenv local 3.6 3.7
      - run: poetry install
      - run: tox

workflows:
  version: 2
  test:
    jobs:
      - test
