version: 2

jobs:
  test_38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo pip install tox
      - run: sudo pip install -r requirements.txt
      - run: tox -e py38-django22
      - run: tox -e py38-django30

workflows:
  version: 2
  test:
    jobs:
      - test_38
