version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: tox

workflows:
  version: 2
  test:
    jobs:
      - test
