version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
    steps:
      - checkout
  test:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: tox

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
