name: Feature Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened] # Default
  push:
    branches:
      - main

jobs:
  test:
    runs-on: sfdc-ubuntu-latest
    strategy:
      matrix:
        environment: ["py38-django22", "py38-django30"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Run Tests
        run: |
          pip install -r requirements.txt
          tox -e ${{ matrix.environment }}


